su: Treat an empty passwd field as invalid
shadow-maint/shadow pull request #315
Opened 2021-03-14 18:14 UTC by lanodan

Otherwise it's treated like the “require no password” clause while it probably
should be treated like a normal su that can't validate anyway.

A similar change should be done for USE_PAM.

2021-03-15 01:17 UTC, lanodan commented
btw this is to avoid the possibility of accidents with logging to UID-0, I would be fine with allowing no-password for other users but  you should put a dumb password instead of nothing.  
And maybe there is multi-user scripts using this (non-documented?) feature but I don't think there is a good use case for this.

2021-03-15 07:38 UTC, t8m commented
This will certainly break existing legitimate use-cases even for the uid 0 account. I'd recommend to make it configurable via login.defs. Perhaps with the default to be as in the proposed patch but with possibility to revert.

2021-03-15 09:00 UTC, lanodan commented
Nice idea. I think I'll put the default to "allow for non-UID 0" to avoid a change that would be too destructive for not much gains.

2021-03-22 22:48 UTC, relax-pad requested changes
Ok![image](https://user-images.githubusercontent.com/79824872/112068189-50e1dc80-8b61-11eb-9767-a2d08052ea8b.png)-

2021-03-22 22:52 UTC, relax-pad requested changes
Hey

2021-03-23 23:32 UTC, hallyn commented on etc/login.defs
> +# Set to "no" to not prevent for any account (dangerous, historical default)
Conceptually sounds good, thanks.  I'll just need to do a closer code review.

2021-03-29 03:16 UTC, merged