usermod: respect --prefix for --gid option
shadow-maint/shadow pull request #691
Opened 2023-03-26 01:21 UTC by floppym

2023-03-28 10:27 UTC, ikerexxe requested changes
Do you mind providing more information in the commit message as to why this change is necessary? I guess it's because we'd like to change the user's primary group by providing the GID value instead of its name, but it isn't very clear right now.

2023-03-28 15:10 UTC, floppym commented
I've updated the commit message.

2023-03-28 15:32 UTC, hallyn approved these changes

2023-03-29 07:05 UTC, ikerexxe approved these changes
Thanks for the explanation. Merging.

2023-03-29 07:05 UTC, merged