lib/string/sprintf.h: Add SNPRINTF() macro
shadow-maint/shadow pull request #865
Opened 2023-12-04 13:38 UTC by alejandro-colomar

It wraps snprintf(3) so that it performs some steps that one might forget, or might be prone to accidents:

-  It calculates the size of the destination buffer, and makes sure it's an array (otherwise, using sizeof(s) would be very bad).

-  It calculates if there's truncation or an error, returning -1 if so.

BTW, this macro doesn't have any issues of double evaluation, because sizeof() doesn't evaluate its argument (unless it's a VLA, but then the static_assert(3) within NITEMS() makes sure VLAs are not allowed).

This macro is very similar to STRTCPY(), defined in lib/string/strtcpy.h.

2023-12-06 12:07 UTC, ferivoz requested changes
The argument type for sizes of *snprintf function wrappers should match the type of the *snprintf functions themselves, i.e. use `size_t` instead of `int`.

2023-12-06 12:07 UTC, ferivoz commented on lib/string/sprintf.c
> +    const char *restrict fmt, ...);
The function `snprintf` takes `size_t` for `size` and `snprintf_` should do the same.

2023-12-06 12:07 UTC, ferivoz commented on lib/string/sprintf.c
> +    const char *restrict fmt, va_list ap);
The function `vsnprintf` takes `size_t` for `size` and `vsnprintf_` should do the same.

2023-12-06 12:07 UTC, ferivoz commented on lib/string/sprintf.h
> +inline int snprintf_(char *restrict s, int size, const char *restrict fmt, ...);
Switch from `int` to `size_t` here as well.

2023-12-06 12:07 UTC, ferivoz commented on lib/string/sprintf.h
> +    va_list ap);
Switch from `int` to `size_t` here as well.

2023-12-06 12:07 UTC, ferivoz commented on lib/string/sprintf.h
> +snprintf_(char *restrict s, int size, const char *restrict fmt, ...)
Switch from `int` to `size_t` here as well.

2023-12-06 12:07 UTC, ferivoz commented on lib/string/sprintf.h
> +vsnprintf_(char *restrict s, int size, const char *restrict fmt, va_list ap)
Switch from `int` to `size_t` here as well.

2023-12-06 12:07 UTC, ferivoz commented on lib/string/sprintf.h
> +	if (len >= size)
Test for `len` being negative first. If it is not, `len` should be casted to `size_t` for comparison.

2023-12-06 15:10 UTC, alejandro-colomar commented
v2 changes:

-  Use size_t instead of int.  [@ferivoz ]

```
$ git range-diff shadow/master gh/SNPRINTF SNPRINTF 
1:  4cee77f3 = 1:  4cee77f3 lib/string/sprintf.h: Add SNPRINTF() macro
2:  da5b05e3 ! 2:  7f580102 lib/string/sprintf.[ch]: Add [v]snprintf_()
    @@ Commit message
         These functions are like [v]snprintf(3), but return -1 on truncation,
         which makes it easier to test.  In fact, the API of swprintf(3), which
         was invented later than snprintf(3), and is the wide-character version
    -    of it, is identical to this snprintf_(), except that it uses size_t
    -    instead of int (we're limited to int because we call snprintf(3)
    -    internally).
    +    of it, is identical to this snprintf_().
     
         snprintf(3) is iseful in two cases:
     
    @@ Commit message
     
         Use these functions to implement SNPRINTF().
     
    +    Cc: Samanta Navarro <ferivoz@riseup.net>
         Signed-off-by: Alejandro Colomar <alx@kernel.org>
     
      ## lib/string/sprintf.c ##
    @@ lib/string/sprintf.c
      extern inline int xvasprintf(char **restrict s, const char *restrict fmt,
          va_list ap);
     +
    -+extern inline int snprintf_(char *restrict s, int size,
    ++extern inline int snprintf_(char *restrict s, size_t size,
     +    const char *restrict fmt, ...);
    -+extern inline int vsnprintf_(char *restrict s, int size,
    ++extern inline int vsnprintf_(char *restrict s, size_t size,
     +    const char *restrict fmt, va_list ap);
     
      ## lib/string/sprintf.h ##
    @@ lib/string/sprintf.h: inline int xasprintf(char **restrict s, const char *restri
      inline int xvasprintf(char **restrict s, const char *restrict fmt, va_list ap);
      
     +format_attr(printf, 3, 4)
    -+inline int snprintf_(char *restrict s, int size, const char *restrict fmt, ...);
    ++inline int snprintf_(char *restrict s, size_t size, const char *restrict fmt,
    ++    ...);
     +format_attr(printf, 3, 0)
    -+inline int vsnprintf_(char *restrict s, int size, const char *restrict fmt,
    ++inline int vsnprintf_(char *restrict s, size_t size, const char *restrict fmt,
     +    va_list ap);
     +
      
    @@ lib/string/sprintf.h: xvasprintf(char **restrict s, const char *restrict fmt, va
      
      
     +inline int
    -+snprintf_(char *restrict s, int size, const char *restrict fmt, ...)
    ++snprintf_(char *restrict s, size_t size, const char *restrict fmt, ...)
     +{
     +  int      len;
     +  va_list  ap;
    @@ lib/string/sprintf.h: xvasprintf(char **restrict s, const char *restrict fmt, va
     +
     +
     +inline int
    -+vsnprintf_(char *restrict s, int size, const char *restrict fmt, va_list ap)
    ++vsnprintf_(char *restrict s, size_t size, const char *restrict fmt, va_list ap)
     +{
     +  int  len;
     +
     +  len = vsnprintf(s, size, fmt, ap);
    -+  if (len >= size)
    -+          len = -1;
    ++  if (len == -1)
    ++          return -1;
    ++  if ((size_t) len >= size)
    ++          return -1;
     +
     +  return len;
     +}
3:  53b9ce34 = 3:  4c05a222 tests/unit/test_snprintf.c: Test SNPRINTF()
4:  c40f5554 = 4:  7491eb5e lib/, src/: snprintf(3) already terminates strings with NUL
5:  a7dd370d = 5:  051c1d9c src/login.c: Group preprocessor conditionals
6:  ec192bcf = 6:  60d18515 lib/, src/: Align variable definitions
7:  a532dc8f = 7:  1ed8a3d0 lib/, src/: Use SNPRINTF() instead of its pattern
```

2023-12-13 19:07 UTC, alejandro-colomar commented
v3 changes:

-  Rebase to master

```
$ git range-diff master..gh/SNPRINTF shadow/master..SNPRINTF 
1:  4cee77f3 = 1:  e203133a lib/string/sprintf.h: Add SNPRINTF() macro
2:  7f580102 = 2:  49b98e10 lib/string/sprintf.[ch]: Add [v]snprintf_()
3:  4c05a222 = 3:  47ee15d9 tests/unit/test_snprintf.c: Test SNPRINTF()
4:  7491eb5e < -:  -------- lib/, src/: snprintf(3) already terminates strings with NUL
5:  051c1d9c < -:  -------- src/login.c: Group preprocessor conditionals
6:  60d18515 < -:  -------- lib/, src/: Align variable definitions
7:  1ed8a3d0 ! 4:  314fbe5a lib/, src/: Use SNPRINTF() instead of its pattern
    @@ src/login.c: static /*@observer@*/const char *get_failent_user (/*@returned@*/co
     +  char           *pam_user = NULL;
     +  pid_t          child;
      #else
    +   bool is_console;
    +   struct spwd *spwd = NULL;
      # if defined(ENABLE_LASTLOG)
     -  char ptime[80];
     +  char           ptime[80];
      # endif
    --  bool is_console;
    --  struct spwd *spwd = NULL;
    -+  bool           is_console;
    -+  struct spwd    *spwd = NULL;
      #endif
      #if defined(RLOGIN)
     -  char term[128] = "";
```

2023-12-13 19:13 UTC, alejandro-colomar commented
v3b changes:

-  Update some commit message.

```
$ git range-diff shadow/master gh/SNPRINTF SNPRINTF 
1:  e203133a ! 1:  6060b0e5 lib/string/sprintf.h: Add SNPRINTF() macro
    @@ Commit message
         sizeof() doesn't evaluate its argument (unless it's a VLA, but then the
         static_assert(3) within NITEMS() makes sure VLAs are not allowed).
     
    -    This macro is very similar to STRTCPY(), defined in lib/strtcpy.h.
    +    This macro is very similar to STRTCPY(), defined in
    +    <lib/string/strtcpy.h>.
     
         Signed-off-by: Alejandro Colomar <alx@kernel.org>
     
2:  49b98e10 = 2:  889e3224 lib/string/sprintf.[ch]: Add [v]snprintf_()
3:  47ee15d9 = 3:  90eb02e9 tests/unit/test_snprintf.c: Test SNPRINTF()
4:  314fbe5a = 4:  39e81022 lib/, src/: Use SNPRINTF() instead of its pattern
```

2023-12-14 22:46 UTC, alejandro-colomar commented
v4 changes:

-  Rebase to master

```
$ git range-diff 6060b0e5^..gh/SNPRINTF shadow/master..SNPRINTF 
1:  6060b0e5 = 1:  e908cd20 lib/string/sprintf.h: Add SNPRINTF() macro
2:  889e3224 = 2:  534e7e1f lib/string/sprintf.[ch]: Add [v]snprintf_()
3:  90eb02e9 = 3:  adb5c1e0 tests/unit/test_snprintf.c: Test SNPRINTF()
4:  39e81022 ! 4:  67cdcb62 lib/, src/: Use SNPRINTF() instead of its pattern
    @@ lib/commonio.c: static void dec_lock_count (void)
      
      int commonio_unlock (struct commonio_db *db)
      {
    --  char lock[1024];
    -+  char  lock[1024];
    +-  char lock[1029];
    ++  char  lock[1029];
      
        if (db->isopen) {
                db->readonly = true;
```

2023-12-15 11:21 UTC, ikerexxe reviewed
Just one small comment. Can you rename `test_snprintf.c` to `test_sprintf.c`? In my mind it makes more sense to create a test file per implementation file. This way we can test several functions in the same file.

2023-12-15 11:40 UTC, alejandro-colomar commented
v5 changes:

-  Rename file [@ikerexxe ]
-  Use C99 comments for copyright, which save 2 lines.

```
$ git range-diff shadow/master gh/SNPRINTF SNPRINTF 
1:  e908cd20 = 1:  e908cd20 lib/string/sprintf.h: Add SNPRINTF() macro
2:  534e7e1f = 2:  534e7e1f lib/string/sprintf.[ch]: Add [v]snprintf_()
4:  67cdcb62 = 3:  e3c595f8 lib/, src/: Use SNPRINTF() instead of its pattern
3:  adb5c1e0 ! 4:  4c609ad5 tests/unit/test_snprintf.c: Test SNPRINTF()
    @@ Metadata
     Author: Alejandro Colomar <alx@kernel.org>
     
      ## Commit message ##
    -    tests/unit/test_snprintf.c: Test SNPRINTF()
    +    tests/unit/test_sprintf.c: Test SNPRINTF()
     
         Signed-off-by: Alejandro Colomar <alx@kernel.org>
     
    @@ tests/unit/Makefile.am: TESTS = $(check_PROGRAMS)
      
      check_PROGRAMS = \
          test_chkname \
    -+    test_snprintf \
    ++    test_sprintf \
          test_strncpy \
          test_strtcpy \
          test_xasprintf
    @@ tests/unit/Makefile.am: test_logind_LDADD = \
          $(LIBSYSTEMD) \
          $(NULL)
      
    -+test_snprintf_SOURCES = \
    ++test_sprintf_SOURCES = \
     +    ../../lib/string/sprintf.c \
    -+    test_snprintf.c \
    ++    test_sprintf.c \
     +    $(NULL)
    -+test_snprintf_CFLAGS = \
    ++test_sprintf_CFLAGS = \
     +    $(AM_FLAGS) \
     +    $(NULL)
    -+test_snprintf_LDFLAGS = \
    ++test_sprintf_LDFLAGS = \
     +    $(NULL)
    -+test_snprintf_LDADD = \
    ++test_sprintf_LDADD = \
     +    $(CMOCKA_LIBS) \
     +    $(NULL)
     +
    @@ tests/unit/Makefile.am: test_logind_LDADD = \
          test_strncpy.c \
          $(NULL)
     
    - ## tests/unit/test_snprintf.c (new) ##
    + ## tests/unit/test_sprintf.c (new) ##
     @@
    -+/*
    -+ * SPDX-FileCopyrightText: 2023, Alejandro Colomar <alx@kernel.org>
    -+ * SPDX-License-Identifier: BSD-3-Clause
    -+ */
    ++// SPDX-FileCopyrightText: 2023, Alejandro Colomar <alx@kernel.org>
    ++// SPDX-License-Identifier: BSD-3-Clause
     +
     +
     +#include <config.h>
```

2023-12-15 12:17 UTC, ikerexxe commented on lib/pwauth.c
> +		SNPRINTF(prompt, cp, user);
Isn't the format specifier already a constant?

2023-12-15 12:25 UTC, alejandro-colomar commented on lib/pwauth.c
> +		SNPRINTF(prompt, cp, user);
It complains because it's not a string literal.

2023-12-15 15:25 UTC, ikerexxe commented on lib/pwauth.c
> +		SNPRINTF(prompt, cp, user);
I see, then we can dismiss this alert.

2023-12-15 15:41 UTC, ikerexxe approved these changes
LGTM, so merging

2023-12-15 15:41 UTC, merged